default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: amazonia_tintas_development
  username: <%= ENV['DB_USERNAME'] || "amazoniatintas" %>
  password: <%= ENV['DB_PASSWORD'] || "Amazonia11235813" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: amazonia_tintas_test
  username: <%= ENV['DB_USERNAME'] || "amazoniatintas" %>
  password: <%= ENV['DB_PASSWORD'] || "Amazonia11235813" %>
  host: <%= ENV['DB_HOST'] || "localhost" %>
  port: <%= ENV['DB_PORT'] || 5432 %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || "amazonia_tintas_production" %>
  username: <%= ENV['DB_USERNAME'] || "amazoniatintas" %>
  password: <%= ENV['DB_PASSWORD'] || "Amazonia11235813" %>
  host: <%= ENV['DB_HOST'] || "db" %>
  port: <%= ENV['DB_PORT'] || 5432 %>
